- name: Install required packages for MariaDB
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - python-mysqldb
    - default-libmysqlclient-dev
    - php-mysql

- name: Enable firewall rules for MySQL
  ufw:
    rule: allow
    port: 3306

- name: Start MySQL service and enable it
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create database
  mysql_db:
    name: "{{ mysql_bdd }}"
    state: present

- name: Create user with privileges
  mysql_user:
    name: "{{ mysql_usuer }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: localhost
    state: present

- name: Copy database
  copy:
    src: bdd.sql
    dest: /tmp/bdd.sql

- name: Insert database
  mysql_db:
     name: incidencias
     state: import
     target: /tmp/bdd.sql
  notify:
   - Restart mariadb

- name: Copy shell script for backup
  copy:
    src: backup.sh
    dest: /etc/backup/

- name: Generate a cron task to run the sh
  cron:
    name: "Backup"
    minute: "0"
    hour: "12"
    day: "15"
    job: "sh /home/cliente/backup.sh"

# Copiar el my.cnf
