## The mariadb package is installed with the apt module because it is installed with the package module
## it misplaces the main mysql configuration file in debian and generates errors
## and that's why I separate it and install it with another module different from the rest of the necessary packages

- name: Install package MariaDB with APT
  apt:
    name: mariadb-server
    state: present

- name: Install required packages for MariaDB
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - default-libmysqlclient-dev
    - php-mysql

- name: Enable firewall rules for MySQL
  ufw:
    rule: allow
    port: '3306'

- name: Start MySQL service and enable it
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create user with privileges
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: localhost
    state: present
  no_log: True

## If we save the output in a register, all the secret data such as passwords and usernames are exposed
## To keep confidential values out of registries, use the option no_log: True

- name: Create database
  mysql_db:
    name: "{{ mysql_bdd }}"
    state: present
  register: db_created

## We register the output of the command in a variable that will be used
## later to condition the action of another task

- name: Copy database
  copy:
    src: bdd.sql
    dest: /tmp/bdd.sql

- name: Insert database
  mysql_db:
    name: incidencias
    state: import
    target: /tmp/bdd.sql
  when: db_created.changed

- name: Copy shell script for backup
  copy:
    src: backup.sh
    dest: /etc/backup/

- name: Generate a cron task to run the sh
  cron:
    name: "Backup"
    minute: "0"
    hour: "12"
    day: "15"
    job: "sh /home/cliente/backup.sh"


