- name: Instalación paquetes necesarios
  package: name="{{ item[0] }}" state="{{ item[1] }}"
  with_nested:
    - [ 'ufw', 'apache2', 'php', 'libapache2-mod-php', 'php-mcrypt' ]
    - [ 'present']

# poner mensaje debug en caso de error 
        
# PHP-MYCRIPT --> Esta extension es un reemplazo para el comando crypt de unix, es un medio para encriptar 
#archivos de linux

- name: Habilitar firewall
  ufw:
    state: enabled

- name: Habilitar reglas firewall | SSH | HTTP | HTTPS
  ufw:
    rule: '{{ item[0] }}'
    port: '{{ item[1] }}'
    proto: '{{ item[2] }}'
  with_nested:
    - [ 'allow' ]
    - [ 22, 80, 443 ]
    - [ 'tcp' ]


#Es necesario el modulo de apache2 --> Habilita o deshabilita un módulo específico del servidor web Apache2
#https://docs.ansible.com/ansible/latest/modules/apache2_module_module.html 
#Usando este modulo, usamos un controlador de tareas para reiniciar apache2 

- name: Habilitar modulo apache2
  apache2_module: name=rewrite state=present
  notify: 
    - Restart apache2 
    
-  name: Habilitar modulo SSL
   apache2_module: 
     name: ssl 
     state: present
   notify:
     - Restart apache2
 
- name: Habilitar servicio apache 
  service:
    name: apache2
    enabled: yes

- name: Configuración ports.conf
  lineinfile:
    dest: /etc/apache2/ports.conf
    regexp: "^Listen "
    line: "Listen 443"

- name: Configuracion hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ ip_cliente }}		cesa.com"
 
- name: Generar llave y cert 
  shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/llave-apache.key -out /etc/ssl/certs/certificado-apache.crt -subj "/C=ES/ST=Madrid/O=Cesa.com/Email=admin@cesa.com" 

#Revisar si las variables van con comillas o no hace falta 

- name: Crear estructura directorio raiz
  file: 
     path: /var/www/{{ dominio }}/public_html
     state: directory
     mode: '0755'
           
- name: Asignar permisos al usuario root
  shell: chown -R $USER:$USER /var/www/{{ dominio }}/public_html
   

- name: Copiar  index
  copy:
    src: index.php
    dest: /var/www/{{ dominio }}/public_html/
    mode: '0664'

#Configuración del virtualhost + backup 

- name: Crear archivo del virtualhost
  template:
     src: 000-default.conf.j2 
     dest: /etc/apache2/sites-available/{{ dominio }}.conf
     backup: yes

- name: Copiar fichero conf principal
  template:
     src: apache2.conf.j2
     dest: /etc/apache2/apache2.conf
     backup: yes 
        
- name: Habilitar cambios 
  command: a2ensite {{ dominio }}
  notify:
  - Restart apache2 
    
#Vamos a crear un fragmento de configuración de apache con ajustes de cifrado seguro 
#dentro de /etc/apache2/conf-available creamos un archivo que se llame ssl-params.conf

- name: Crear ssl-params.conf
  copy:
   src: ssl-params.conf.j2
   dest: /etc/apache2/conf-available/ssl-params.conf
     
#He modificado las directivas asi que de momento esto se queda en deshuso     
#- name: Creación del archivo de configuración de SSL 
  #template:
    #src: default-ssl.conf.j2
    #dest: /etc/apache2/sites-available/default-ssl.conf

- name: Habilitar cambios apache | SSL 
  apache2_module: name=ssl state=present
  notify:
   - Restart apache2

- name: Habilitar cambios apache | Headers 
  apache2_module: name=headers state=present
  notify:
   - Restart apache2

#- name: Habilitar host virtual SSL
# command: a2ensite default-ssl

- name: Habilitar ssl-params 
  command: a2enconf ssl-params
  notify:
   - Restart apache2




