- name: Update repositories
  apt:
    update_cache: yes
    #Is the equivalent of the command apt-get update
    force_apt_get: yes
    #This parameter is specified for not use aptitude command
    cache_valid_time: 3600

- name: Upgrading all the apt packages
  apt:
    upgrade: dist
    force_apt_get: true

- name: Install common packages
  apt:
    name: ufw
    state: present

- name: Enable firewall
  ufw:
    state: enabled

#- name: Install python-apt dependency
#  apt:
#    name: python-apt
#    state: latest
