---
mysql_bdd: saludo
mysql_user: admin_1
mysql_password: "Admin12345"
domain: cesa.com
...


#Este fichero al tener una variable que contiene la contraseña lo voy a cifrar con el comando
# ansible-vault encrypt